### ISSUE TITLE
Images don't copy on deploy

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/StreamDeckDashboard#1]

**Comment by CrypticEngima** [comment]
I couldn't push my changes to the Repo (tried to branch and create pull request but kept failing authorization) but the Fix is :

Change lines 16 and 17 in file RegisterPluginAndStratStreamDeck.ps1 to read
 
Copy-Item -Path $bindir -Exclude '.vs' -Recurse -Destination $destDir -Force

This will make sure the files are copied and updated every build.

The issue was in the piping of information from one command to the other powershell was somehow losing the sub files in images directory(i'm trying to workout why). This simplification of the commands on line 16 and 17 to one copy-item command in my opinion makes the ps1 easier to read.

**Comment by hugodahl** [comment]
The referenced pull request, [#84](https://github.com/FritzAndFriends/StreamDeckToolkit/pull/84) in the [FritzAndFriends/StreamDeckToolkit](https://github.com/FritzAndFriends/StreamDeckToolkit/) project corrects the issue with the deployed template.
